### PR TITLE
Add missing comments configuration for gitcommit

### PR DESCRIPTION
**Pull request by somini**
This copies the comment configuration from gitrebase files into the
gitcommit filetype.

### CODE REVIEW

**Comment by tpope** [comment]
You need to adjust `b:undo_ftplugin` too.

**Comment by somini** [comment]
Should I squash this into a single commit?

**Comment by tpope** [comment]
Yep.

**Comment by somini** [comment]
Done.

**Comment by somini** [comment]
:+1:

**Pull request merged**
