### PR TITLE
Treat `.git/ISSUE_EDITMSG` as a `gitcommit`

### PR DESCRIPTION
**Pull request by teoljungberg**
The file is created via `hub(1)` when you create a new issue via `hub
issue create`.

### CODE REVIEW

**Comment by teoljungberg** [comment]
What's your thought on this @tpope?

**Comment by tpope** [comment]
I'm leaning towards saying this should go in Rhubarb.

**Comment by teoljungberg** [comment]
I'm OK with that. Should I move any of the other rhubarb specific files aswell? Which I guess the only other one is `.git/PULLREQ_EDITMSG`.

**Comment by tpope** [comment]
Yes. I don't think I knew that was a `hub` thing when I merged.

**Comment by teoljungberg** [comment]
The files I can see that `hub(1)` generates are:

- ISSUE_EDITMSG
- PULLREQ_EDITMSG
- RELEASE_EDITMSG

I've opened https://github.com/tpope/vim-rhubarb/pull/32 in rhubarb for this.

Should I make a follow-up PR here to delete handling `PULLREQ_EDITMSG` as a `gitcommit`?

**Comment by tpope** [comment]
Please.

**Comment by teoljungberg** [comment]
Done in #54

**Pull request closed without merging**
