### PR TITLE
Always set textwidth

### PR DESCRIPTION
**Pull request by gtd**
When I have a global textwidth set it is for general coding style
concerns and almost certainly should not apply to git commit messages.
I think it's reasonable therefore to always set textwidth, and if
someone wants to break convention let them do so forcibly.

### CODE REVIEW

**Comment by nisanth074** [comment]
@tpope 

Hi there,

We regularly write commit messages longer than 72 characters in our projects so its easy for our non developer team members (like our product designer) to peruse code and understand commits that change a particular file. Commit message conciseness is not important for us and the 72 character limit vim-git enforces is unhelpful in our case.

Is there a way to turn off the character limit or override it in my `.vimrc`?

I tried adding
```
set textwidth=0
```
to the last line in my vim file but it seems like vim-git overrides it when vim starts
```
:verbose set textwidth
```
```
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
  textwidth=72
        Last set from /usr/local/Cellar/vim/8.0.0633/share/vim/vim80/ftplugin/gitcommit.vim
Press ENTER or type command to continue
```

 Thanks for your time.

**Comment by tpope** [comment]
I'm not going to pretend to understand your use case, but you can add `setlocal textwidth=0` to `.vim/after/ftplugin/gitcommit.vim`.

**Comment by gtd** [comment]
@nisanth074 following the commit standard should never make commit messages harder to read, it should always be easier.  For instance, 50-char summary line never gets truncated in any tool you look at.

I understand if the designers can't be bothered to write specifically formatted commit message in their tooling, but they're not using vim are they?

**Comment by tpope** [comment]
Yeah I agree, you're basically breaking Git because... designers can't read wrapped text? I think the root of this is probably a misunderstanding about the subject/body format of a commit message. The first line should be a short summary, like an email subject, and then if you have more details elaborate in the body, after a blank line.

**Comment by davidosomething** [comment]
@gtd you can also set a gitcommit template and add a modeline to it

**Comment by nisanth074** [comment]
Thanks for suggesting the workaround Tim.
> I'm not going to pretend to understand your use case, but you can add setlocal textwidth=0 to .vim/after/ftplugin/gitcommit.vim.

I understand why the setting exists but wanted to politely request for a way to disable it (I couldn't find a way to disable it myself). The `textwidth=72` setting not only hard breaks long commit subjects but it also hard breaks long commit bodies at 72 characters. Unfortunately, this causes commit bodies to appear weirdly in Desktop tools like SourceTree

supportbee-rails__git_

> following the commit standard should never make commit messages harder to read, it should always be easier. For instance, 50-char summary line never gets truncated in any tool you look at.

**Comment by gtd** [comment]
@nisanth074 sure some tools provide soft-wrapping, but for the ones that don't the problems with long lines are far worse than the problems of extra newlines on the ones that do.  And even the ones that do still are suboptimal without 50-char summary lines:

cloudapp annotation 2017-06-12 at 10 40 19 pm

I understand there will be non-technical users who can't be bothered, but developers should really get on board.  [Tim wrote this up](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) quite nicely nearly a decade ago, and Chris Beams later elucidated further with an even [more epic post](https://chris.beams.io/posts/git-commit/).  If those don't convince you, then I rest my case, but at least I tried.

**Pull request merged**
