### PR TITLE
Match hash references in commit bodies

### PR DESCRIPTION
**Pull request by jparise**
Highlight these matches as Identifiers and disable spell checking.

### CODE REVIEW

**Comment by hugomg** [comment]
At some point in the future Git will also support SHA-256 hashes, which can be up to 64 hexadecimal characters. I think it wouldn't hurt to increase the maximum length of the pattern to 64 instead of 40.

(This is just a drive-by suggestion. I am not one of the project maintainers)

**Comment by tpope** [comment]
This also highlights common English words like "added". A safe compromise would be to highlight 40+ characters only.

**Comment by jparise** [comment]
@tpope that's a great point. I changed this to match 40+ characters, per your suggestion. I also added the `display` syntax attribute.

**Comment by tpope** [comment]
Let's use the name `Hash`, not `SHA1`, as in the other file types.

**Comment by jparise** [comment]
Updated to match at least 40 characters, although it's a little less useful for many commit messages where abbreviated hashes are often used. I'm not sure there's a way to have it both ways, though.

**Comment by hugomg** [comment]
What do you think about only matching hexadecimal sequences that have at least one number? That is the case for the vast majority of hashes.

    \x\{6,\}\&\x*\d\x*

**Comment by tpope** [comment]
Send another PR for that if you want. I'll get around to evaluating it eventually.

**Pull request merged**
